using System;
using System.Data;


namespace Day7Task4
{
    //here no default constructor
    public class Date
    {
        public int year { get; set; }
        public int month { get; set; }
        public int day { get; set; }
        public Date(int _year, int _month, int _day)
        {
            year = _year;
            month = _month;
            day = _day; 
        }
        public override string ToString()
        {
            return $"{year},{month},{day}";
        }
    }


    //here an default constructor
    public struct date
    {
        public int year { get; set; }
        public int month { get; set; }
        public int day { get; set; }
        public date(int _year, int _month, int _day)
        {
            year = _year;
            month = _month;
            day = _day;
        }
        public override string ToString()
        {
            return $"Date : {year}/{month}/{day}";
        }
    }
    public class program
    {
       public static int Main()
        {
            //Since the Date class has a constructor that takes parameters, no default constructor will be generated by the compiler.
            Date D = new Date();
            Console.WriteLine(D);

            date d =new date();
            Console.WriteLine(d);
            return 0;
        }
    }
}
